### ISSUE TITLE
不支持FreeBSD / Windows(?)

### ISSUE THREAD

**Issue by Ra1ny-Yuki** [zyxgad/rawinput_mcdr#1]
尝试于FreeBSD安装该插件，加载时提示模块termios缺少属性，尝试卸载该插件或关闭服务端时，MCDR会疯狂地跳log，至于log中的操作MCDR是否真的实际执行了尚不可知

其中一次MCDR的运行log见：https://paste.ubuntu.com/p/DPNkzjBFrQ/

Fallen说在Windows上一输入就EOF Error

望早日拿出一个多平台通用的实现

以上

**Comment by Ra1ny-Yuki** [comment]
补充一点，在linux上启用后删除命令行中已输入的中文仍然只删除半个（说仍然是因为MCDR本身就这样）

**Comment by zyxgad** [comment]
en,这是由于命令行的原因,你可以翻看源码发现我是简单粗暴的使用填充空格的方式"删除"字符,并没有判断字符实际长度,这个bug我会尽快修改,谢谢反馈



在 2021-08-07 07:45:16，"Ra1ny_Yuki" ***@***.***> 写道：

补充一点，在linux上启用后删除命令行中已输入的中文仍然只删除半个（说仍然是因为MCDR本身就这样）

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Ra1ny-Yuki** [comment]
补充一下，mcdr2.0已经有了类似的解决方案了，使用prompt-toolkit模块。如果这插件还要继续做下去应该考虑一下向下兼容MCDR1.x和0.x（老版本还是有钉子户的

**Comment by zyxgad** [comment]
> 尝试于FreeBSD安装该插件，加载时提示模块termios缺少属性，尝试卸载该插件或关闭服务端时，MCDR会疯狂地跳log，至于log中的操作MCDR是否真的实际执行了尚不可知
> 
> 其中一次MCDR的运行log见：https://paste.ubuntu.com/p/DPNkzjBFrQ/
> 
> Fallen说在Windows上一输入就EOF Error
> 
> 望早日拿出一个多平台通用的实现
> 
> 以上

我看了一下，疯狂跳interrupt日志是由于不停的在readline当中raise KeyboardInterrupt导致的，这个问题以及通过修改 `ConsoleHandler.tick`这个方法解决.
至于windows报错EOFError可能是以前的代码当中有些不适用于windows的地方(就是代码逻辑写错了)导致出错, 不过由于我暂时还没有windows系统所以也无法测试新版本是否跨windows平台

**Comment by zyxgad** [comment]
所有您说的问题基本都在v1.1.1版本中修复，包括:
- 对windows系统的支持
- 对于宽字符的粗暴处理进一步优化（即对中文字符的删除等等）
- 自动识别mcdr 2.0+ advanced_console是否被启用，如果启用则自动禁用本插件
对于windows系统仍然存在一个找不到原因的bug
- 无法使用MCDR指令
